# Generated by Django 5.0.6 on 2024-07-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_userprofile_correo_alter_userprofile_cc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
    ]
